### ISSUE TITLE
请关一下主站的 Google Analytics 或者改用自己的 GA 衡量 ID

### ISSUE THREAD

**Issue by r-value** [TLEer/Gitalkcomments#27]
我跑过来是因为我在我的 GA 报表里发现了这个页面...

请不要直接用别人的 GA 分析 ID...

~~虽然确实有我忘记配 GA 数据流的源站限制的原因qwq~~

建议把整个配置文件读一遍把不是自己的都改掉(

**Comment by TLEer** [comment]
@r-value fixed
我确实忘了XD
